GerenciamentoOnline/GerenciamentoOnline/GerenciamentoOnline/Controllers/GraficoController.cs
using ProjetoModeloDDD.Domain.DAO.Entities;
using ProjetoModeloDDD.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NHibernate.Criterion;
using GerenciamentoOnline.Auxiliares;
using ProjetoModelo.Entities;
using kardapio.Suprimentos;
using static ProjetoModeloDDD.Domain.Entities.Lixeira;
using ProjetoModeloDDD.Domain.DAO.Auxiliar;

namespace GerenciamentoOnline.Controllers
{
    public class GraficoController : Controller
    {
        // GET: Grafico
        public ActionResult Index()
        {
            return View();
        }

        public static string GetDropDownLixeiras()
        {
            string cSelect = "<select class='lixeiras'>";
            try
            {
                Lixeira[] lixeira = LixeiraDAO.FindAll();

                foreach (Lixeira tipoAc in lixeira)
                {
                    cSelect += "<option value=\"" + tipoAc.Id + "\">" + tipoAc.Descricao + "</option>";
                }
            }
            catch (Exception e)
            {
                MetodosGlobais.SaveExceptionError(e, "Home/GetDropDownLixeiras");
            }
            cSelect += "</select>";

         
            return cSelect;
        }

        [AllowAnonymous]
        public MvcHtmlString GetDrowDownLixeira()
        {
            string chtml = GetDropDownLixeiras();

            return new MvcHtmlString(chtml);
        }

        //public static string GetDropDownRegiaos()
        //{
        //    string cSelect = "";
        //    string cSelect1 = "<select class='regiao'>";
        //    string cSelect2 = "<option value=\"";
        //    string cSelect3 = "\">";
        //    string cSelect4 = "</option>";
        //    string cSelect5 = "</select>";
        //    int cSelect6 = 0;
        //    string cSelect7 = "";
        //    string cSelect9 = "";
        //    try
        //    {
        //        Regiao[] regiao = RegiaoDAO.FindAll();

        //        foreach (Regiao tipoAc in regiao)
        //        {
        //            cSelect6 = tipoAc.Id.Value;
        //            cSelect7 = tipoAc.Descricao;

        //            if (cSelect7 == cSelect9)
        //            {
        //                cSelect9 = "";
        //            }
        //            else
        //            {
        //                cSelect9 = cSelect7;
        //                cSelect = cSelect1 + cSelect2 + cSelect6 + cSelect3 + cSelect7 + cSelect4 + cSelect5;
        //            }
        //        }
        //    }
        //    catch (Exception e)
        //    {
        //        MetodosGlobais.SaveExceptionError(e, "Home/GetDropDownRegiao");
        //    }

        //    return cSelect;
        //}

        //[AllowAnonymous]
        //public MvcHtmlString GetDropDownRegiao()
        //{
        //    string chtml = GetDropDownRegiaos();

        //    return new MvcHtmlString(chtml);
        //}

        public static string GetDropDownBairros()
        {
            string cSelect = "<select class='bairro'>";
            try
            {
                Bairro[] bairro = BairroDAO.FindAll();

                foreach (Bairro tipoAc in bairro)
                {
                    cSelect += "<option value=\"" + tipoAc.Id + "\">" + tipoAc.Descricao + "</option>";
                }
            }
            catch (Exception e)
            {
                MetodosGlobais.SaveExceptionError(e, "Home/GetDropDownRegiao");
            }
            cSelect += "</select>";

            return cSelect;
        }

        [AllowAnonymous]
        public MvcHtmlString GetDropDownBairro()
        {
            string chtml = GetDropDownBairros();

            return new MvcHtmlString(chtml);
        }

        public static string GetDropDownCidades()
        {
            string cSelect = "<select class='cidade'>";
            try
            {
                Cidade[] cidade = CidadeDAO.FindAll();

                foreach (Cidade tipoAc in cidade)
                {
                    cSelect += "<option value=\"" + tipoAc.Id + "\">" + tipoAc.Nome + "</option>";
                }
            }
            catch (Exception e)
            {
                MetodosGlobais.SaveExceptionError(e, "Home/GetDropDownRegiao");
            }
            cSelect += "</select>";

            return cSelect;
        }

        [AllowAnonymous]
        public MvcHtmlString GetDropDownCidade()
        {
            string chtml = GetDropDownCidades();

            return new MvcHtmlString(chtml);
        }


    }
}

GerenciamentoOnline/GerenciamentoOnline/GerenciamentoOnline/Views/Grafico/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Graficos";

}

<script>
    @*$('.Lixera').click(function () {
        $('.Lixeira')).after( @{ Html.RenderAction("GetDrowDownLixeira", "Grafico"); });
     });*@
</script>
<style>
    .GraficosAvancados {
        padding-left: 15px;
        margin-top: 2px;
        margin-bottom: -28px;
    }
    .Lixera {
        margin: 14px;
    }
    .Bairro {
        padding-left: 267px;
        margin-top: -84px;
    }
    .Cidade {
        padding-left: 521px;
        margin-top: -80px;
    }
    .Regiao {
        padding-left: 773px;
        margin-top: -80px;
    }

</style>

<div id="content">

    <div id="content-header">
        <div id="breadcrumb"><a href="#" title="Dashboard" class="tip-bottom"><i class="icon-home"></i> Dashboard</a> <a href="#" class="current">Graficos Avançados</a></div>
    </div>
    <div class="container-fluid">
        <br>
        <h1 class="GraficosAvancados">Graficos Avançados</h1>
        <div class="widget-content">
            <div class="row-fluid">
                <div class="span12">
                    <div class="widget-box">
                        <div class="widget-title">
                            <span class="icon"> <i class="icon-signal"></i> </span>
                            <h5>Filtros</h5>
                        </div>
                        <div class="Lixera">
                            <h5>Escolha a Lixeira</h5>
                            @{ Html.RenderAction("GetDrowDownLixeira", "Grafico"); }
                        </div>
                        @*<div class="Regiao">
                            <h5> Região</h5>
                            @{ Html.RenderAction("GetDropDownRegiao", "Grafico"); }
                        </div>*@
                        <div class="Bairro">
                            <h5> Bairro</h5>
                            @{ Html.RenderAction("GetDropDownBairro", "Grafico"); }
                        </div>
                        <div class="Cidade">
                            <h5> Cidade</h5>
                            @{ Html.RenderAction("GetDropDownCidade", "Grafico"); }
                        </div>
                        <br>
                    </div>
                </div>
            </div>
            @*<div Class="btn-group">
                <button class="btn">Lixeiras</button>
                <button data-toggle="dropdown" class="btn dropdown-toggle">
                    <span class="caret"></span>
                </button>

                <ul class='dropdown-menu'>
                    @{ Html.RenderAction("GetDrowDownLixeira", "Grafico"); }
                </ul>
            </div>*@

            <div class="row-fluid">
                <div class="span12">
                    <div class="widget-box">
                        <div class="widget-title">
                            <span class="icon"> <i class="icon-signal"></i> </span>
                            <h5>Quantidade de Lixo</h5>
                        </div>
                        <div class="widget-content">
                            <div id="placeholder2"></div>
                            @*<p>
                                Tempo de Atualização:
                                <input id="updateInterval" type="text" value="" style="text-align: right; width:5em">
                                Mili Segundos
                            </p>*@
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <div class="widget-box">
                        <div class="widget-title">
                            <span class="icon"> <i class="icon-signal"></i> </span>
                            <h5>Histórico Mensal</h5>
                        </div>
                        <div class="widget-content">
                            <div class="bars"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="widget-box widget-plain">
                <div class="center">
                    <ul class="stat-boxes2">
                        <li>
                            <div class="left peity_bar_neutral">
                                <span>
                                    <span style="display: none;">2,4,9,7,12,10,12</span>
                                    <canvas width="50" height="24"></canvas>
                                </span>+10%
                            </div>
                            <div class="right"> <strong>15598</strong> Visits </div>
                        </li>
                        <li>
                            <div class="left peity_line_neutral">
                                <span>
                                    <span style="display: none;">10,15,8,14,13,10,10,15</span>
                                    <canvas width="50" height="24"></canvas>
                                </span>10%
                            </div>
                            <div class="right"> <strong>150</strong> New Users </div>
                        </li>
                        <li>
                            <div class="left peity_bar_bad">
                                <span>
                                    <span style="display: none;">3,5,6,16,8,10,6</span>
                                    <canvas width="50" height="24"></canvas>
                                </span>-40%
                            </div>
                            <div class="right"> <strong>4560</strong> Orders</div>
                        </li>
                        <li>
                            <div class="left peity_line_good">
                                <span>
                                    <span style="display: none;">12,6,9,23,14,10,17</span>
                                    <canvas width="50" height="24"></canvas>
                                </span>+60%
                            </div>
                            <div class="right"> <strong>5672</strong> Active Users </div>
                        </li>
                        <li>
                            <div class="left peity_bar_good"><span>12,6,9,23,14,10,13</span>+30%</div>
                            <div class="right"> <strong>2560</strong> Register</div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>